spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://43.251.17.158:3306/wj?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: rxy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.wangchuanan.wjj.pojo
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

logging:
  level:
    com:
      wangchuanan:
        wjj:
          dao: debug


